# Generated by Django 4.2.18 on 2025-02-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=56, null=True)),
                ('work_phone', models.CharField(max_length=56, null=True)),
                ('service_number', models.CharField(max_length=56, null=True)),
                ('status', models.CharField(max_length=56)),
                ('own_number', models.CharField(max_length=56)),
                ('home_number', models.CharField(max_length=56)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
