# Generated by Django 4.2.18 on 2025-02-23 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Sektor Rahbar', 'Sektor Rahbar'), ('Boshqarma', 'Boshqarma')], default='Boshqarma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, choices=[('109', 'Bulung‘ur tumani'), ('110', 'Jomboy tumani'), ('111', 'Ishtixon tumani'), ('112', 'Kattaqo‘rg‘on tumani'), ('113', 'Kattaqo‘rg‘on shahri'), ('114', 'Qo‘shrabot tumani'), ('115', 'Narpay tumani'), ('116', 'Nurabod tumani'), ('117', 'Oqdaryo tumani'), ('118', 'Payariq tumani'), ('119', 'Pastarg‘om tumani'), ('120', 'Paxtachi tumani'), ('121', 'Samarqand tumani'), ('122', 'Samarqand shahri'), ('123', 'Toyloq tumani'), ('124', 'Urgut tumani'), ('125', 'Samarqand viloyati')], max_length=200, null=True)),
                ('can_add_user', models.BooleanField(default=False)),
                ('can_edit_user', models.BooleanField(default=False)),
                ('can_delete_user', models.BooleanField(default=False)),
                ('can_view_all', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=56)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')])),
                ('own_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('Sektor Rahbar', 'Sektor Rahbar'), ('Aparat hodim', 'Aparat hodim'), ('Boshqarma', 'Boshqarma')], default='Boshqarma', max_length=20)),
                ('birthday', models.DateField()),
                ('service_number', models.CharField(blank=True, max_length=56, null=True)),
                ('position', models.CharField(max_length=56)),
                ('home_number', models.CharField(blank=True, max_length=56, null=True)),
                ('district', models.CharField(choices=[('109', 'Bulung‘ur tumani'), ('110', 'Jomboy tumani'), ('111', 'Ishtixon tumani'), ('112', 'Kattaqo‘rg‘on tumani'), ('113', 'Kattaqo‘rg‘on shahri'), ('114', 'Qo‘shrabot tumani'), ('115', 'Narpay tumani'), ('116', 'Nurabod tumani'), ('117', 'Oqdaryo tumani'), ('118', 'Payariq tumani'), ('119', 'Pastarg‘om tumani'), ('120', 'Paxtachi tumani'), ('121', 'Samarqand tumani'), ('122', 'Samarqand shahri'), ('123', 'Toyloq tumani'), ('124', 'Urgut tumani'), ('125', 'Samarqand viloyati')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='contacts.management')),
            ],
        ),
    ]
