# Generated by Django 4.2.18 on 2025-02-13 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('1', 'Sektor Rahbar'), ('3', 'Boshqarma')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_user', models.BooleanField(default=False)),
                ('can_view_own_district', models.BooleanField(default=True)),
                ('can_view_all', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.role')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=56)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')])),
                ('own_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('1', 'Sektor Rahbar'), ('2', 'Aparat hodim'), ('3', 'Boshqarma')], default='3', max_length=20)),
                ('service_number', models.CharField(blank=True, max_length=56, null=True)),
                ('position', models.CharField(max_length=56)),
                ('home_number', models.CharField(blank=True, max_length=56, null=True)),
                ('district', models.CharField(choices=[('109', 'Bulung‘ur tumani'), ('110', 'Jomboy tumani'), ('111', 'Ishtixon tumani'), ('112', 'Kattaqo‘rg‘on tumani'), ('113', 'Kattaqo‘rg‘on shahri'), ('114', 'Qo‘shrabot tumani'), ('115', 'Narpay tumani'), ('116', 'Nurabod tumani'), ('117', 'Oqdaryo tumani'), ('118', 'Payariq tumani'), ('119', 'Pastarg‘om tumani'), ('120', 'Paxtachi tumani'), ('121', 'Samarqand tumani'), ('122', 'Samarqand shahri'), ('123', 'Toyloq tumani'), ('124', 'Urgut tumani')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='contacts.management')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.role')),
            ],
        ),
    ]
