# Generated by Django 4.2.18 on 2025-02-08 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_personcontact_work_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+998XXXXXXXXX'.", regex='^\\+998\\d{9}$')]),
        ),
    ]
