# Generated by Django 4.2.18 on 2025-02-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_personcontact_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personcontact',
            old_name='status',
            new_name='position',
        ),
    ]
